### ISSUE TITLE
No Bot Logging

### ISSUE THREAD

**Issue by AnthonySil** [WidovV/cs2-connectionlogs#1]
I have bots join the server. is there a way to not log the bots. like ignore connected with ip `127.0.0.1`

**Comment by WidovV** [comment]
I'll fix it later today :D

**Comment by WidovV** [comment]
Should be fixed now @AnthonySil

**Comment by AnthonySil** [comment]
Thanks @WidovV I downloaded the zipped file to get the latest update and copied over the compiled files. restarted the server but i still get bot logging.

**Comment by WidovV** [comment]
Thanks for feedback @AnthonySil 

I'm gonna check it out tomorrow after work, Cuz bots shouldnt appear :D

**Comment by WidovV** [comment]
@AnthonySil 
Okay so i forgot a bot check last time on disconnect, but i tested it multiple times with lots of bots and none occured, so it should be good now™️
Some memory usage/garbage collection is also improved

**Comment by AnthonySil** [comment]
@WidovV  Great Thanks! I uploaded the latest compiled files and works now.
